{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uber",
    "module": "common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0-SNAPSHOT-plain.jar",
          "url": "common-1.0-SNAPSHOT-plain.jar",
          "size": 2620,
          "sha512": "9ded6feb6893ff59cbbfa808187c53dac6492982c1fed92f2af050c369d94d34b02557da2cfce56a04c5d58de40d27cf7ef81484602fecc3989a379d66555929",
          "sha256": "b61ffc38636e3b9b2aa69ef3b3261ea2a84b05978229285035c5436bfdc11d28",
          "sha1": "57b66ecd772e8a2e3b1ec8f41ee3fa2912067abc",
          "md5": "4def26bb5bea66bb0c07349d4731c7a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.3.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0-SNAPSHOT-plain.jar",
          "url": "common-1.0-SNAPSHOT-plain.jar",
          "size": 2620,
          "sha512": "9ded6feb6893ff59cbbfa808187c53dac6492982c1fed92f2af050c369d94d34b02557da2cfce56a04c5d58de40d27cf7ef81484602fecc3989a379d66555929",
          "sha256": "b61ffc38636e3b9b2aa69ef3b3261ea2a84b05978229285035c5436bfdc11d28",
          "sha1": "57b66ecd772e8a2e3b1ec8f41ee3fa2912067abc",
          "md5": "4def26bb5bea66bb0c07349d4731c7a4"
        }
      ]
    }
  ]
}
